# 1.1 Numpy Basics

##### <center>Import Libraries for Later</center>

In [15]:
import numpy as np

### 1.1.1 Vectors (1D Arrays)

In [20]:
# Lets start by creating some vectors, or 1D matrices explicitly
a = np.array([3, 6, 9])
b = np.array([1, 2, 3]) 
# Print out the vectors
print(f"a: {a}\nb: {b}\n")

a: [3 6 9]
b: [1 2 3]



In [21]:
# Lets create vectors using the arange() method
# Note: arange(start, end, step)
c = np.arange(3) 
d = np.arange(5, 8) 
e = np.arange(2, 8, 2) 
# Print out the vectors
print(f"c: {c}\nd: {d}\ne: {e}")

c: [0 1 2]
d: [5 6 7]
e: [2 4 6]


In [23]:
# The colon (:) can be used to call specific parts of a vector
# Initialize vector "f" for use later
f = np.arange(10)
print(f"f: {f}")

# Create vectors from vector f
g = f[:5] # Call the first 5 elements of f
h = f[:] # Returns every element of f
i = f[5:] # Returns the last 5 elements of f  
print(f"g: {g}\nh: {h}\ni: {i}")

f: [0 1 2 3 4 5 6 7 8 9]
g: [0 1 2 3 4]
h: [0 1 2 3 4 5 6 7 8 9]
i: [5 6 7 8 9]


In [37]:
# The colon can also be used in some special cases
j = f[:-4] # Returns every element except the last 4
k = f[3:8] # Returns the 3rd to 8th element (including the 8th)
print(f"j: {j}\nk: {k}")

j: [0 1 2 3 4 5]
k: [3 4 5 6 7]


### 1.1.2 Multidimensional Matrices

##### 1.1.2.1 2D Arrays

In [42]:
# Lets start by creating some 2D Matrcies
a2D = np.array([[2, 4], [6, 8]]) # Initialize 2x2 Matrix
b2D = np.array([[3, 6, 9], [12, 15, 18], [21, 24, 27]]) # Initialize 3x3 Matrix
# Print out the matrices
print(f"a2D: \n{a2D}\nb2D: \n{b2D}\n")

a2D: 
[[2 4]
 [6 8]]
b2D: 
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]



In [47]:
# To create 2D arrays using arange(), we need to reshape vectors
# First create the vector
cVector = np.arange(16)
# Then use the reshape() method
# Note: reshape(array, newshape)
c2D = np.reshape(cVector, [4, 4]) # The new matrix will be 4x4
print(f"cVector: \n{cVector}\nc2D: \n{c2D}\n")

cVector: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
c2D: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



In [75]:
# There are some special functions we can use to create useful 2D matrices
zeros = np.zeros([2, 2], dtype=int) # Note: zeros(shape, data type)
ones = np.ones([2, 2], dtype=int) # Note: ones(shape, data type)
eye = np.eye(2, 2, 0, dtype=int) # Note: eye(rows, columns, diagonal index, data type)
diag = np.diag((3, 4)) # Note: diag(v, k), where v is a list of the number going on the kth diagonal, and k is the diagonal to go on
print(f"zeros: \n{zeros}\nones: \n{ones}\ndiag: \n{diag}\neye: \n{eye}")

zeros: 
[[0 0]
 [0 0]]
ones: 
[[1 1]
 [1 1]]
diag: 
[[3 0]
 [0 4]]
eye: 
[[1 0]
 [0 1]]


In [76]:
# We can also combine matrices using a special command, which will be useful for later computations
block = np.block([[ones, zeros], [eye, diag]])
print(f"block: \n{block}")

block: 
[[1 1 0 0]
 [1 1 0 0]
 [1 0 3 0]
 [0 1 0 4]]


##### 1.1.2.2 Higher Dimensional Matricies

In [78]:
# Numpy also supports higher dimensional Matrix, here is a 3D Matrix
a3D = np.array([[[0, 1, 2], [3, 4, 5], [6, 7, 8]], [[9, 10, 11], [12, 13, 14], [15, 16,17]], [[18, 19, 20], [21, 22, 23], [24, 25, 26]]])
print(f"a3D: \n{a3D}")

a3D: 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
