# 1.3 Linear Regression

## 1.3.1 QR Decomposition

QR Decomposition can be used to solve the linear least squares problem and is the basis for the QR algorithm. The $Q$ is an orthogonal matrix, and $R$ is an upper trianglar matrix:

\begin{align}
QQ^T = I \;\;\;\;\;\;\;\;\;\; Q^T = Q^{-1} \;\;\;\;\;\;\;\;\;\;
R = 
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\
0 & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
0 & 0 & \cdots & a_{nn}\\
\end{bmatrix}\;\;\;\;\;\\ \\
\end{align}

QR Decomposition follows the form $A = QR$, and in some cases is easier seen in the form $A^T = R^TQ^T $. 

In [56]:
# SciPy is a much more powerful linear algebra tool in python, we'll be switching to that for functions
# We will still use NumPy for array declaration
import numpy as np
from scipy import linalg
np.set_printoptions(precision=3, suppress=True)
# QR decomposition can be done in one simple command
A = np.array([[2, -6, 3], [1, 12, 33], [2, 9, -6]], dtype=int)
Q, R = linalg.qr(A)
Q, R = Q * -1, R * -1
print(f"A:\n{A}")
print(f"Q:\n{Q}")
print(f"R:\n{R}")

A:
[[ 2 -6  3]
 [ 1 12 33]
 [ 2  9 -6]]
Q:
[[ 0.667 -0.667  0.333]
 [ 0.333  0.667  0.667]
 [ 0.667  0.333 -0.667]]
R:
[[ 3.  6.  9.]
 [-0. 15. 18.]
 [-0. -0. 27.]]


In [62]:
# We can use these arrays and verify some properties above
# A = QR
QR = np.matmul(Q, R)
# I = QQ^T
QQT = np.matmul(Q, np.transpose(Q))
# AT = RTQT
AT = np.transpose(A)
ATcalc = np.matmul(np.transpose(R), np.transpose(Q))
print(f"QR:\n{QR}")
print(f"QQT:\n{QQT}")
print(f"AT:\n{AT}")
print(f"ATcalc:\n{ATcalc}")

QR:
[[ 2. -6.  3.]
 [ 1. 12. 33.]
 [ 2.  9. -6.]]
QQT:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
AT:
[[ 2  1  2]
 [-6 12  9]
 [ 3 33 -6]]
ATcalc:
[[ 2.  1.  2.]
 [-6. 12.  9.]
 [ 3. 33. -6.]]


## 1.3.2 Least-Squares Problems

Let $A \in \mathbb{R}^{n*m}$ be an $n*m$ matrix, and $b \in \mathbb{R}^n$ be a vector. The system $Ax=b$ is consistant if there exists a set $K$ of n-tuple solutions $s$, such that $s = (s_1, \ldots, s_n) \in \mathbb{R}^n$ satisfying $As = b$. If the solution set $K$ is empty, the system is inconsistant (i.e. if $K \neq \emptyset$, the system is consistent, if $K = \emptyset$ the system is inconsistent). When $n=m$, we can use the inverse $A^{-1}$ to solve the system; however, when $n > m$, $A^{-1}$ does not exist. We can still solve this by finding the solution to the following least squares problem:

\begin{gather*}
\min_{x \in \mathbb{R}^m} || Ax-b|| \\
\text{The solution to this satisfies:}
\\
A^TAx=A^Tb \text{ and } Rx^*=Q^Tb, \text{ where } x^* \text{ is the solution that can be found using back substitution.}
\end{gather*}

## 1.3.3 Linear Regression

Given a set of input data points $\{(x_i,y_i)\}^n_{i=1}$, where $x_i=(x_{i1},\ldots,x_{id})^T$ is a column vector, we can find an affine function (a function thats composed of a linear function plus a constant) to fit the data (i.e. an affine function that is the line of best fit). This can be done by finding some coefficients $\beta_j$ that minimizes the following:

\begin{gather*}
\sum^n_{i=1}(y_i-\hat{y_i})^2 \\
\hat{y_i} = \beta_0+\sum^d_{j=1}\beta_jx_{ij}
\end{gather*}

This can be viewed as the predicted values of the linear model with coefficients $\beta_j$. The problem can be transformed to the following least-squares problem:
\begin{gather*}
\min_\beta ||y-A\beta||^2
\end{gather*}